# Generated by Django 5.0.6 on 2024-05-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_team_ferme'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ferme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.ferme'),
        ),
    ]
