# Generated by Django 5.0.6 on 2024-05-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_team_ferme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cin',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
