# Generated by Django 5.0.6 on 2024-05-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('address', models.CharField(max_length=1024)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
