# Generated by Django 5.0.6 on 2024-05-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferme',
            name='name',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
